### ISSUE TITLE
bitnami redmine-3.2.0-0 install faild

### ISSUE THREAD

**Issue by walkwolf** [planio-gmbh/redmine_wiki_toc#1]
Help!. I run follow command to install the plugin, then get error msg:

```
cd $installdir
./use_redmine
cd apps/redmine/htdocs
rake redmine:plugins:migrate NAME=redmine_wiki_toc RAILS_ENV=production
```

The error info:

```
bash-4.1$ rake redmine:plugins:migrate NAME=redmine_wiki_toc  RAILS_ENV=production
Migrating redmine_wiki_toc (Redmine Wiki table of contents plugin)...
== 20120817053412 AddPositionToWikiPages: migrating ===========================
-- add_column(:wiki_pages, :position, :integer, {:null=>false, :default=>1})
   -> 0.0349s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

wrong number of arguments (2 for 1)/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation.rb:327:in 'update_all'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:8:in 'update_all'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:8:in 'block (4 levels) in up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:8:in 'each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:8:in 'each_with_index'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:8:in 'block (3 levels) in up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:7:in 'each_value'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:7:in 'block (2 levels) in up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:51:in 'block (2 levels) in find_each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:51:in 'each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:51:in 'block in find_each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:124:in 'find_in_batches'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:50:in 'find_each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:9:in 'find_each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:6:in 'block in up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'block in transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in 'within_new_transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in 'transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in 'transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/plugins/redmine_wiki_toc/db/migrate/20120817053412_add_position_to_wiki_pages.rb:5:in 'up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:571:in 'up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:611:in 'exec_migration'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:592:in 'block (2 levels) in migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:591:in 'block in migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in 'with_connection'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:590:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:768:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:998:in 'block in execute_migration_in_transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:1046:in 'ddl_transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:997:in 'execute_migration_in_transaction'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:959:in 'block in migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in 'each'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:955:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:823:in 'up'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:801:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:481:in 'migrate_plugin'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:453:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:464:in 'migrate'
/home/redmine/redmine-3.2.0-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in 'block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

```

**Comment by jkraemer** [comment]
as the readme states, this plugin is only compatible with Redmine 2.x at the moment.
